### ISSUE TITLE
ImportError: No module named weak_symmetric_matrix

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC2#4]
The `GTC.weak_symmetric_matrix` module no longer exists; however, this is imported in `context.py` and `test_weak_symmetric_matrix.py`

Most likely, an `ImportError` was not raised in your local repo because there is still a cached `weak_symmetric_matrix.pyc` file in the `GTC` directory.

**Comment by BlairDHall** [comment]
This is a test module that is not used any more
