### ISSUE TITLE
UncertainComplex.__nonzero__ inconsistent with UncertainReal.__nonzero__

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC2#6]
The `UncertainComplex.__nonzero__` method returns a value that is inconsistent with `UncertainReal.__nonzero__`

For example,
```python
>>> from GTC import ureal, ucomplex
>>> ur = ureal(0, 0)
>>> bool(ur)
False
>>> uc = ucomplex(0j, 0)
>>> bool(uc)
True
```
Based on the _TODO_ comment in the `UncertainReal.__nonzero__` method I'm not sure what the intended behaviour is for what `bool(UN)` should return, but I think that the returned value should be consistent for `UncertainComplex` and `UncertainReal`

**Comment by BlairDHall** [comment]
The implementation for UncertainComplex was a mistake (``==`` instead of ``!=``), which is now corrected.
