### ISSUE TITLE
remove 'label' argument from Context.uncertain_complex

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC2#7]
The method signature for `Context.uncertain_complex` requires a _label_ to be passed in. 
```python
def uncertain_complex(self,r,i,label):
    if label is None:
        return UncertainComplex(r,i)
    else:
        r.label = "{}_re".format(label)
        i.label = "{}_im".format(label)
            
        uc = UncertainComplex(r,i)
        uc.label = label
            
        return uc         
```
However, if _label_ is not `None` then trying to set the _label_ for a `UncertainReal` would result in an `AttributeError: can't set attribute`.

I would recommend that the _label_ argument be removed from the method signature. 
```python
def uncertain_complex(self, r, i):
    return UncertainComplex(r, i)
```
There are 10 functions that call `Context.uncertain_complex` and all 10 of these functions pass a value of `None` for the _label_. We would need to remove the `None` argument from each of the 10 method calls. The 10 functions are located in `lib_real.py`

1. _add_re_z
2. _add_z_re
3. _div_re_z
4. _div_z_re
5. _mul_re_z
6. _mul_z_re
7. _pow_re_z
8. _pow_z_re
9. _sub_re_z
10. _sub_z_re

**Comment by BlairDHall** [comment]
After refactoring the lib_rea.py, lib_complex.py and complex.py modules, this issue no longer exists.
