### ISSUE TITLE
Unresolved reference 'x' in _is_uncertain_complex_constant()

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC2#8]
The function `lib_complex._is_uncertain_complex_constant` uses the parameter `x` when constructing the error message for `RuntimeError`. However, `x` is not defined.

```python
        raise RuntimeError(
            "UncertainComplex required: {!r}".format(x)
        )
```

**Comment by BlairDHall** [comment]
`x` changed to `z`
